Repository Ocelot-Social-Community/Ocelot-Social, pull requests merged in 2020-12, with the labels that each got.

#3899 feat: Export User Data
  backend/src/middleware/permissionsMiddleware.js
  backend/src/schema/resolvers/userData.js
  backend/src/schema/resolvers/userData.spec.js
  backend/src/schema/types/type/UserData.gql
  webapp/assets/_new/icons/svgs/download.svg
  webapp/graphql/User.js
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/package.json
  webapp/pages/settings.vue
  webapp/pages/settings/data-download.vue
  webapp/yarn.lock
Labels: Github Import

#4086 Throw Error When No Cookie Can Be Set
  webapp/components/LoginForm/LoginForm.vue
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/store/auth.js
Labels: bug

#4079 chore: 🍰 Replace node-sass with sass
  webapp/package.json
  webapp/yarn.lock
Labels: backend, core, dependencies

#4083 feat: Node Version Recommendation In backend/README.md
  backend/README.md
Labels: documentation

#4047 feat: 🔥 Displaying Social Media Favicons On Profile Page
  webapp/components/SocialMedia/SocialMedia.spec.js
  webapp/components/SocialMedia/SocialMedia.vue
  webapp/pages/profile/_id/_slug.vue
Labels: feature

#4091 Name of Cookie Is Set in metadata.js
  webapp/constants/metadata.js
  webapp/nuxt.config.js
  webapp/plugins/apollo-config.js
  webapp/store/auth.js
Labels: bug

#4102 docu_design
  docu/dashboard/dashboard.desktop_1920x1080.png
  docu/desktop_1920x1080.template.svg
  docu/footer/footer.desktop_1920x1080.png
  docu/ocelot.desktop_1920x1080.svg
  docu/register/register.flow.drawio
  docu/register/register.flow.png
  docu/register/register1.desktop_1920x1080.png
  docu/register/register2.desktop_1920x1080.png
  docu/register/register3.desktop_1920x1080.png
  docu/register/register4.desktop_1920x1080.png
  docu/register/register5.desktop_1920x1080.png
  docu/register/register6.desktop_1920x1080.png
Labels: documentation
