Repository Ocelot-Social-Community/Ocelot-Social, pull requests merged in 2021-06, with the labels that each got.

#4461 docs: 🍰 Correct Discord Links And Divers
  .github/ISSUE_TEMPLATE/question.md
  CONTRIBUTING.md
  README.md
Labels: bug, documentation

#4466 docs: 🍰 Correct 'Contribution.md'
  CONTRIBUTING.md
Labels: documentation

#4452 chore: [WIP] 🍰 New Deployment With 'base' And 'code' Docker Images
  .github/workflows/publish.yml
  backend/Dockerfile
  backend/package.json
  docker-compose.override.yml
  docker-compose.test.yml
  docker-compose.yml
  webapp/Dockerfile
  webapp/Dockerfile.maintenance
  webapp/constants/metadata.js
Labels: core, devops, docker, refactor

#4474 fixed wrong env variable
  backend/src/config/index.js
Labels: backend, bug

#4475 chore: 🍰 Release v1.0.4
  CHANGELOG.md
  backend/package.json
  package.json
  webapp/package.json
Labels: devops
