Repository Ocelot-Social-Community/Ocelot-Social, pull requests merged in 2021-04, with the labels that each got.

#4337 Clean env, docker & workflow
  .github/workflows/test.yml
  backend/src/config/index.js
Labels: backend, docker, refactor

#4330 jwt_expiretime
  backend/.env.template
  backend/src/config/index.js
  backend/src/jwt/encode.js
Labels: backend, devops, feature

#4331 readme_update
  CHANGELOG.md
  README.md
  backend/package.json
  package.json
  webapp/package.json
Labels: documentation, refactor

#4336 fix: Email Confirmation-Link When An Invite-Code Is Given
  CHANGELOG.md
  backend/package.json
  backend/src/middleware/email/emailMiddleware.js
  backend/src/middleware/email/templateBuilder.js
  backend/src/middleware/email/templates/signup.html
  backend/src/schema/resolvers/registration.js
  package.json
  webapp/components/Registration/RegistrationSlider.vue
  webapp/package.json
  webapp/pages/registration.vue
Labels: feature

#4316 feat: 🍰 Remove More-Info Of Post
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/locales/es.json
  webapp/locales/fr.json
  webapp/locales/it.json
  webapp/locales/nl.json
  webapp/locales/pl.json
  webapp/locales/pt.json
  webapp/locales/ru.json
  webapp/pages/post/_id.vue
  webapp/pages/post/_id/_slug/more-info.vue
  webapp/pages/post/_id/_slug/take-action.vue
Labels: frontend

#4350 refactor: 🍰 Refactor E-Mail Templates
  backend/src/middleware/email/templateBuilder.js
  backend/src/middleware/email/templates/emailVerification.html
  backend/src/middleware/email/templates/resetPassword.html
  backend/src/middleware/email/templates/wrongAccount.html
Labels: backend, bug, refactor

#4367 frontend + backend coverage tests
  .github/workflows/test.yml
  backend/package.json
  docker-compose.test.yml
  webapp/package.json
Labels: frontend
