Repository Ocelot-Social-Community/Ocelot-Social, pull requests merged in 2021-02, with the labels that each got.

#4184 Fix cookie
  webapp/config/index.js
  webapp/nuxt.config.js
Labels: bug, frontend

#4186 Backend Unit Tests via CI & Run tests in parallel
  .github/workflows/ci.yml
  backend/Dockerfile
  docker-compose.override.yml
  docker-compose.test.yml
  webapp/Dockerfile
Labels: devOps, docker, refactor

#4191 refactor: Remove Catgeories From Post Teaser
  webapp/components/PostTeaser/PostTeaser.vue
Labels: bug, frontend, refactor

#3928 feat: 🍰 Allow Only Supported Image File Formats
  webapp/components/ImageUploader/ImageUploader.spec.js
  webapp/components/ImageUploader/ImageUploader.vue
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/locales/es.json
  webapp/locales/fr.json
  webapp/locales/it.json
  webapp/locales/nl.json
  webapp/locales/pl.json
  webapp/locales/pt.json
  webapp/locales/ru.json
Labels: feature

#4185 Fix locations
  backend/src/middleware/permissionsMiddleware.js
  backend/src/schema/resolvers/locations.js
  backend/src/schema/resolvers/users/location.js
  backend/src/schema/resolvers/users/location.spec.js
  backend/src/schema/types/type/Location.gql
  webapp/.env.template
  webapp/graphql/location.js
  webapp/pages/settings/index.spec.js
  webapp/pages/settings/index.vue
Labels: bug, refactor

#4194 Clean GitHub folder
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/devops_ticket.md
  .github/ISSUE_TEMPLATE/refactor_tickets.md
  .github/semantic.yml
  .github/stale-disabled.yml
  .github/workflows/test.yml
Labels: devops, refactor

#4195 publish workflow
  .github/workflows/publish.yml
  CHANGELOG.md
  backend/Dockerfile
  backend/package.json
  docker-compose.yml
  docu/deploy-structure.drawio
  docu/deploy-structure.png
  neo4j/Dockerfile
  package.json
  scripts/docker_push.sh
  webapp/Dockerfile
  webapp/package.json
  yarn.lock
Labels: devops, docker, feature, refactor

#4199 feat: Image Cropping Is Optional
  backend/src/db/factories.js
  backend/src/models/Image.js
  backend/src/schema/resolvers/images.js
  backend/src/schema/resolvers/images/images.js
  backend/src/schema/types/type/Image.gql
  webapp/components/ContributionForm/ContributionForm.spec.js
  webapp/components/ContributionForm/ContributionForm.vue
  webapp/components/ImageUploader/ImageUploader.spec.js
  webapp/components/ImageUploader/ImageUploader.vue
  webapp/graphql/Fragments.js
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/pages/post/_id/_slug/index.vue
Labels: bug, frontend

#4136 feat: 🍰 Switch User Role As Admin
  CHANGELOG.md
  backend/package.json
  backend/src/middleware/permissionsMiddleware.js
  backend/src/schema/resolvers/users.js
  backend/src/schema/resolvers/users.spec.js
  backend/src/schema/types/type/User.gql
  package.json
  webapp/graphql/admin/Roles.js
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/package.json
  webapp/pages/admin/users.spec.js
  webapp/pages/admin/users.vue
Labels: administration, feature

#4210 Support newest docker
  .github/workflows/publish.yml
  CHANGELOG.md
  backend/package.json
  package.json
  webapp/package.json
Labels: bug

#4216 fix_webapp_production
  .github/workflows/publish.yml
  CHANGELOG.md
  backend/package.json
  package.json
  webapp/Dockerfile
  webapp/package.json
Labels: bug

#4217 Use original images
  CHANGELOG.md
  backend/package.json
  package.json
  webapp/package.json
  webapp/static/favicon.ico
  webapp/static/icon.png
  webapp/static/img/custom/Logo-Horizontal.svg
  webapp/static/img/custom/logout.svg
  webapp/static/img/custom/password-reset.svg
  webapp/static/img/custom/sign-up.svg
  webapp/static/img/custom/under-maintenance.svg
  webapp/static/img/custom/welcome.svg
Labels: bug, devops

#4221 chore: 🐛 'db:migrate up' By Moving Examples Outside Of Migrations Folder
  backend/src/db/migrations-examples/20200123150105-merge_duplicate_user_accounts.js
  backend/src/db/migrations-examples/20200123150110-merge_duplicate_location_nodes.js
  backend/src/db/migrations-examples/20200127110135-create_muted_relationship_between_existing_blocked_relationships.js
  backend/src/db/migrations-examples/20200206190233-swap_latitude_with_longitude.js
  backend/src/db/migrations-examples/20200207080200-fulltext_index_for_tags.js
  backend/src/db/migrations-examples/20200213230248-add_unique_index_to_image_url.js
  backend/src/db/migrations-examples/20200312140328-bulk_upload_to_s3.js
  backend/src/db/migrations-examples/20200320200315-refactor_all_images_to_separate_type.js
  backend/src/db/migrations-examples/20200323140300-remove_deleted_users_obsolete_attributes.js
  backend/src/db/migrations-examples/20200323160336-remove_deleted_posts_obsolete_attributes.js
  backend/src/db/migrations-examples/20200326160326-remove_dangling_image_urls.js
Labels: administration, bug, devops

#4219 chore: 🍰 Resolve WEBSOCKETS_URI .env Problem
  CHANGELOG.md
  backend/package.json
  package.json
  webapp/config/index.js
  webapp/package.json
  webapp/plugins/apollo-config.js
Labels: devops

#4222 chore: 🐛 Fix Migrations By Migrations Folder Having .gitkeep
  backend/src/db/migrations/.gitkeep
Labels: devops

#4223 Smtp secure option
  CHANGELOG.md
  backend/package.json
  backend/src/config/index.js
  backend/src/middleware/email/emailMiddleware.js
  package.json
  webapp/package.json
Labels: administration, feature

#4225 fix: Query Available Roles As Admin
  backend/src/middleware/permissionsMiddleware.js
  backend/src/schema/resolvers/roles.js
  backend/src/schema/types/enum/UserGroup.gql
  backend/src/schema/types/type/User.gql
  webapp/graphql/admin/Roles.js
  webapp/pages/admin/users.vue
Labels: bug

#4230 fix: css so follow button isn't blocked by adblock
  CHANGELOG.md
  backend/package.json
  package.json
  webapp/components/FollowButton.vue
  webapp/package.json
Labels: bug

#4233 fix: Add Null Migration
  CHANGELOG.md
  backend/package.json
  backend/src/db/migrations/1613589876420-null_mutation.js
  package.json
  webapp/package.json
Labels: bug
