Repository Ocelot-Social-Community/Ocelot-Social, pull requests merged in 2021-03, with the labels that each got.

#4266 dashboard restructuring image
  docu/dashboard/donate+restruturing.png
Labels: documentation

#4218 Correct version style
  .github/workflows/publish.yml
  backend/Dockerfile
  neo4j/Dockerfile
  webapp/Dockerfile
Labels: devops, feature

#4248 feat: 🍰 Count Post Views
  backend/src/db/factories.js
  backend/src/db/migrations/1614023644903-add-clickedCount-to-posts.js
  backend/src/middleware/index.js
  backend/src/middleware/slugifyMiddleware.spec.js
  backend/src/middleware/userInteractions.js
  backend/src/middleware/userInteractions.spec.js
  backend/src/models/Post.js
  backend/src/schema/resolvers/posts.js
  backend/src/schema/resolvers/searches.js
  backend/src/schema/types/type/Post.gql
  webapp/assets/_new/icons/svgs/hand-pointer.svg
  webapp/components/PostTeaser/PostTeaser.spec.js
  webapp/components/PostTeaser/PostTeaser.story.js
  webapp/components/PostTeaser/PostTeaser.vue
  webapp/components/generic/SearchPost/SearchPost.spec.js
  webapp/components/generic/SearchPost/SearchPost.vue
  webapp/components/generic/SearchableInput/SearchableInput.story.js
  webapp/graphql/Fragments.js
  webapp/graphql/Search.js
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/storybook/helpers.js
Labels: backend, devops, frontend

#4255 feat: Count Post Teaser Views
  CHANGELOG.md
  backend/package.json
  backend/src/db/factories.js
  backend/src/db/migrations/1614177130817-add-viewedTeaserCount-to-posts.js
  backend/src/middleware/permissionsMiddleware.js
  backend/src/models/Post.js
  backend/src/schema/resolvers/posts.js
  backend/src/schema/resolvers/searches.js
  backend/src/schema/resolvers/viewedTeaserCount.spec.js
  backend/src/schema/types/type/Post.gql
  package.json
  webapp/components/PostTeaser/PostTeaser.spec.js
  webapp/components/PostTeaser/PostTeaser.story.js
  webapp/components/PostTeaser/PostTeaser.vue
  webapp/components/generic/SearchPost/SearchPost.spec.js
  webapp/components/generic/SearchPost/SearchPost.vue
  webapp/components/generic/SearchableInput/SearchableInput.story.js
  webapp/graphql/Fragments.js
  webapp/graphql/PostMutations.js
  webapp/graphql/Search.js
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/nuxt.config.js
  webapp/package.json
  webapp/plugins/vue-observe-visibility.js
  webapp/storybook/helpers.js
  webapp/test/testSetup.js
  webapp/yarn.lock
Labels: feature

#4168 feat: 🍰 Redesign Registration Process Frontend
  backend/src/schema/resolvers/rewards.spec.js
  webapp/components/ComponentSlider/ComponentSlider.vue
  webapp/components/Registration/CreateUserAccount.story.js
  webapp/components/Registration/RegistrationItemCreateUserAccount.vue
  webapp/components/Registration/RegistrationItemEnterEmail.vue
  webapp/components/Registration/RegistrationItemEnterInvite.vue
  webapp/components/Registration/RegistrationItemEnterNonce.vue
  webapp/components/Registration/RegistrationSlider.story.js
  webapp/components/Registration/RegistrationSlider.vue
  webapp/components/utils/PasswordFormHelper.js
  webapp/locales/de.json
  webapp/locales/en.json
Labels: feature, frontend

#4278 fix: JWT Expires In 2 Years
  backend/src/jwt/encode.js
Labels: bug

#4296 fix: 🍰 Suggestion List Filter
  backend/src/schema/resolvers/users/location.spec.js
  webapp/components/Editor/Editor.spec.js
  webapp/components/Editor/Editor.vue
Labels: bug, frontend

#4301 feat: 🍰 Invite Button
  backend/.env.template
  backend/src/config/index.js
  backend/src/middleware/permissionsMiddleware.js
  backend/src/schema/resolvers/inviteCodes.js
  backend/src/schema/types/type/InviteCode.gql
  webapp/.env.template
  webapp/assets/_new/icons/svgs/copy.svg
  webapp/components/InviteButton/InviteButton.vue
  webapp/components/PageFooter/PageFooter.vue
  webapp/config/index.js
  webapp/layouts/default.vue
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/nuxt.config.js
  webapp/pages/registration/signup.vue
  webapp/plugins/vue-filters.js
Labels: backend, frontend

#4270 feat: 🍰Implement Registration Slider
  backend/src/middleware/email/emailMiddleware.js
  backend/src/middleware/email/templateBuilder.js
  backend/src/middleware/permissionsMiddleware.js
  backend/src/middleware/permissionsMiddleware.spec.js
  backend/src/schema/resolvers/emails.js
  backend/src/schema/resolvers/emails.spec.js
  backend/src/schema/resolvers/helpers/generateNonce.js
  backend/src/schema/resolvers/inviteCodes.js
  backend/src/schema/resolvers/registration.js
  backend/src/schema/resolvers/registration.spec.js
  backend/src/schema/resolvers/transactions/inviteCodes.js
  backend/src/schema/types/type/EmailAddress.gql
  webapp/components/ComponentSlider/ComponentSlider.vue
  webapp/components/EnterNonce/EnterNonce.spec.js
  webapp/components/EnterNonce/EnterNonce.vue
  webapp/components/LoginForm/LoginForm.vue
  webapp/components/Registration/CreateUserAccount.spec.js
  webapp/components/Registration/CreateUserAccount.story.js
  webapp/components/Registration/CreateUserAccount.vue
  webapp/components/Registration/EmailDisplayAndVerify.vue
  webapp/components/Registration/RegistrationItemEnterEmail.vue
  webapp/components/Registration/RegistrationItemEnterNonce.vue
  webapp/components/Registration/RegistrationSlideCreate.vue
  webapp/components/Registration/RegistrationSlideEmail.vue
  webapp/components/Registration/RegistrationSlideInvite.vue
  webapp/components/Registration/RegistrationSlideNoPublic.vue
  webapp/components/Registration/RegistrationSlideNonce.vue
  webapp/components/Registration/RegistrationSlider.story.js
  webapp/components/Registration/RegistrationSlider.vue
  webapp/components/Registration/Signup.spec.js
  webapp/components/Registration/Signup.vue
  webapp/components/utils/TranslateErrorMessage.js
  webapp/graphql/Registration.js
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/locales/es.json
  webapp/locales/fr.json
  webapp/locales/it.json
  webapp/locales/pl.json
  webapp/locales/pt.json
  webapp/locales/ru.json
  webapp/middleware/authenticated.js
  webapp/nuxt.config.js
  webapp/pages/registration.spec.js
  webapp/pages/registration.vue
  webapp/pages/registration/create-user-account.vue
  webapp/pages/registration/enter-nonce.vue
  webapp/pages/registration/signup.vue
Labels: backend, frontend

#4314 fix: 🐛 Fix Wrong Truncation Of Hashtags In Admin List Via Adding 'truncateStr'
  webapp/pages/admin/hashtags.vue
  webapp/plugins/vue-filters.js
Labels: bug, frontend

#4321 v1.0.0
  CHANGELOG.md
  backend/package.json
  package.json
  webapp/package.json
Labels: devops

#4320 fix: 🍰 Fixing The Avatars unwanted Border
  webapp/components/AvatarMenu/AvatarMenu.vue
  webapp/components/_new/generic/UserAvatar/UserAvatar.story.js
  webapp/components/_new/generic/UserAvatar/UserAvatar.vue
  webapp/components/_new/generic/UserAvatar/storybook/critical-avatar-white-background.png
Labels: bug, frontend
