Repository Ocelot-Social-Community/Ocelot-Social, pull requests merged in 2021-05, with the labels that each got.

#4391 correct_docker_tagging
  .github/workflows/publish.yml
  .github/workflows/test.yml
  backend/Dockerfile
  neo4j/Dockerfile
  webapp/Dockerfile
  webapp/Dockerfile.maintenance
Labels: bug, devops

#4393 Coverage
  .github/workflows/test.yml
  webapp/components/ComponentSlider/ComponentSlider.spec.js
  webapp/components/FollowButton.spec.js
  webapp/components/InviteButton/InviteButton.spec.js
  webapp/components/Logo/Logo.spec.js
  webapp/components/Modal.spec.js
  webapp/components/NotificationList/NotificationList.spec.js
  webapp/components/PageFooter/PageFooter.spec.js
  webapp/components/Password/Change.spec.js
  webapp/components/PasswordReset/ChangePassword.spec.js
  webapp/components/PasswordReset/Request.spec.js
  webapp/components/Registration/Signup.spec.js
  webapp/components/ShoutButton.spec.js
  webapp/components/features/ReportsTable/ReportsTable.spec.js
  webapp/components/generic/SearchableInput/SearchableInput.spec.js
  webapp/layouts/basic.spec.js
  webapp/layouts/blank.spec.js
  webapp/layouts/default.spec.js
  webapp/package.json
  webapp/pages/admin.spec.js
  webapp/pages/admin/categories.spec.js
  webapp/pages/admin/donations.spec.js
  webapp/pages/admin/hashtags.spec.js
  webapp/pages/admin/invite.spec.js
  webapp/pages/admin/notifications.spec.js
  webapp/pages/admin/organizations.spec.js
  webapp/pages/admin/pages.spec.js
  webapp/pages/admin/settings.spec.js
  webapp/pages/code-of-conduct.spec.js
  webapp/pages/data-privacy.spec.js
  webapp/pages/imprint.spec.js
  webapp/pages/login.spec.js
  webapp/pages/logout.spec.js
  webapp/pages/moderation.spec.js
  webapp/pages/moderation/index.spec.js
  webapp/pages/password-reset.spec.js
  webapp/pages/password-reset/change-password.spec.js
  webapp/pages/password-reset/enter-nonce.spec.js
  webapp/pages/password-reset/request.spec.js
  webapp/pages/post/_id.spec.js
  webapp/pages/post/_id/_slug/index.spec.js
  webapp/pages/post/create.spec.js
  webapp/pages/post/edit/_id.spec.js
  webapp/pages/profile/_id.spec.js
  webapp/pages/registration.spec.js
  webapp/pages/search/search-results.spec.js
  webapp/pages/settings.spec.js
  webapp/pages/settings/data-download.spec.js
  webapp/pages/settings/delete-account.spec.js
  webapp/pages/settings/embeds.spec.js
  webapp/pages/settings/invites.spec.js
  webapp/pages/settings/languages.spec.js
  webapp/pages/settings/my-email-address/index.spec.js
  webapp/pages/settings/my-organizations.spec.js
  webapp/pages/settings/privacy.spec.js
  webapp/pages/settings/privacy.vue
  webapp/pages/settings/security.spec.js
  webapp/pages/terms-and-conditions-confirm.spec.js
  webapp/pages/terms-and-conditions.spec.js
  webapp/test/fileMock.js
Labels: devops, documentation, frontend

#4370 feat: 🍰 Show Password Component
  webapp/components/LoginForm/LoginForm.vue
  webapp/components/Registration/RegistrationSlideCreate.vue
  webapp/components/ShowPassword/ShowPassword.spec.js
  webapp/components/ShowPassword/ShowPassword.vue
Labels: feature

#4433 chore: 🍰 Refactor Logos
  README.md
  backend/src/config/links.js
  backend/src/config/logos.js
  backend/src/config/metadata.js
  backend/src/middleware/email/templateBuilder.js
  webapp/components/LoginForm/LoginForm.vue
  webapp/components/Logo/Logo.spec.js
  webapp/components/Logo/Logo.vue
  webapp/components/Registration/RegistrationSlider.vue
  webapp/components/_new/generic/BaseCard/BaseCard.story.js
  webapp/constants/links.js
  webapp/constants/logos.js
  webapp/constants/metadata.js
  webapp/layouts/basic.vue
  webapp/layouts/default.vue
  webapp/maintenance/source/pages/index.vue
  webapp/pages/logout.vue
  webapp/pages/password-reset.vue
  webapp/static/img/custom/Logo-Horizontal-Dark.svg
  webapp/static/img/custom/logo-horizontal.svg
  webapp/static/img/custom/logo-squared.svg
  webapp/static/img/custom/password-reset.svg
  webapp/static/img/custom/sign-up.svg
  webapp/static/img/custom/under-maintenance.svg
  webapp/static/img/custom/welcome.svg
Labels: backend, devops, documentation, frontend, refactor

#4435 chore: 🍰 Release v1.0.3
  CHANGELOG.md
  backend/package.json
  package.json
  webapp/maintenance/source/package.json
  webapp/package.json
Labels: core, devops
