Repository Ocelot-Social-Community/Ocelot-Social, pull requests merged in 2022-10, with the labels that each got.

#5418 feat: 🍰 Refine Group Creation And Group Edit
  webapp/components/Group/GroupForm.vue
  webapp/pages/group/edit/_id/members.vue
Labels: frontend

#5380 feat: 🍰 Post In Groups
  backend/src/db/graphql/authentications.js
  backend/src/db/graphql/posts.js
  backend/src/db/seed.js
  backend/src/middleware/permissionsMiddleware.js
  backend/src/middleware/slugifyMiddleware.spec.js
  backend/src/middleware/userInteractions.js
  backend/src/schema/resolvers/groups.js
  backend/src/schema/resolvers/helpers/filterInvisiblePosts.js
  backend/src/schema/resolvers/posts.js
  backend/src/schema/resolvers/postsInGroups.spec.js
  backend/src/schema/resolvers/registration.js
  backend/src/schema/resolvers/searches.js
  backend/src/schema/types/type/Group.gql
  backend/src/schema/types/type/Post.gql
  backend/src/schema/types/type/User.gql
Labels: feature, backend, frontend, Yunite

#5491 feat: 🍰 Make Configurable Header Menu Translatable
  webapp/constants/headerMenu.js
  webapp/layouts/default.vue
Labels: frontend, devops, Yunite

#5503 feat: 🍰 Seed Posts In Groups
  backend/src/db/seed.js
Labels: documentation, feature, Yunite

#5489 refactor: 🍰 Disable Submit Button On group Update Changed Error
  webapp/components/Group/GroupForm.vue
Labels: frontend

#5468 feat: 🍰 Implement Post In Group In Webapp
  .github/workflows/test.yml
  webapp/components/ContributionForm/ContributionForm.spec.js
  webapp/components/ContributionForm/ContributionForm.vue
  webapp/graphql/PostMutations.js
  webapp/graphql/PostQuery.js
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/pages/group/_id/_slug.spec.js
  webapp/pages/group/_id/_slug.vue
  webapp/pages/post/_id.spec.js.old
  webapp/pages/post/_id.vue
  webapp/pages/post/_id/_slug/index.spec.js
  webapp/pages/post/_id/_slug/index.vue
  webapp/pages/post/create.spec.js
  webapp/pages/post/create.vue
  webapp/pages/post/edit/_id.vue
Labels: feature, frontend, features:post, Yunite

#5527 refactor: 🍰 Category Filter In Filter Menu
  webapp/components/FilterMenu/FilterMenu.vue
  webapp/layouts/default.vue
Labels: frontend, refactor

#5525 feat: 🍰 Implement `LOGO_HEADER_CLICK` As Configuration
  webapp/constants/logos.js
  webapp/layouts/default.vue
  webapp/pages/index.vue
Labels: feature, frontend, Yunite

#5524 feat: 🍰 Mobile Footer Menu To Header Menu
  webapp/components/NotificationMenu/NotificationMenu.vue
  webapp/components/PageFooter/PageFooter.vue
  webapp/constants/headerMenu.js
  webapp/layouts/default.vue
Labels: frontend, design

#5543 feat: 🍰 Search For Groups
  .github/workflows/test.yml
  backend/src/middleware/permissionsMiddleware.js
  backend/src/schema/resolvers/searches.js
  backend/src/schema/types/type/Search.gql
  webapp/components/_new/features/SearchResults/SearchResults.spec.js
  webapp/components/_new/features/SearchResults/SearchResults.vue
  webapp/components/generic/SearchGroup/SearchGroup.vue
  webapp/components/generic/SearchableInput/SearchableInput.vue
  webapp/graphql/Fragments.js
  webapp/graphql/Search.js
  webapp/locales/de.json
  webapp/locales/en.json
Labels: feature, backend, frontend

#5552 chore: 🍰 Remove Group Branchs `5059-epic-groups` Separate Auto-Deployment
  .github/workflows/publish.yml
Labels: devops

#4701 feat: [WIP] 🍰 Single Person Org
  backend/README.md
Labels: documentation, feature, backend, frontend, devops

#5574 chore: 🍰 Release v2.1.0
  CHANGELOG.md
  backend/package.json
  package.json
  webapp/maintenance/source/package.json
  webapp/package.json
Labels: devops, Yunite

#5582 feat: 🍰 List All Groups
  backend/src/middleware/permissionsMiddleware.js
  backend/src/schema/resolvers/groups.js
  backend/src/schema/types/type/Group.gql
  webapp/components/AvatarMenu/AvatarMenu.spec.js
  webapp/components/AvatarMenu/AvatarMenu.vue
  webapp/components/Group/GroupButton.vue
  webapp/components/Group/GroupForm.vue
  webapp/graphql/groups.js
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/pages/group/create.vue
  webapp/pages/groups.spec.js
  webapp/pages/groups.vue
  webapp/pages/my-groups.vue
Labels: feature, backend, frontend

#5596 fix: 🍰 Bug In Edit Slug Of Group
  backend/src/middleware/sluggifyMiddleware.js
  backend/src/middleware/slugifyMiddleware.spec.js
  backend/src/schema/resolvers/groups.spec.js
  webapp/components/Group/GroupForm.vue
Labels: feature, backend, frontend, refactor, Yunite

#5583 fix: 🍰 Update Group Avatar After Upload
  backend/src/middleware/excerptMiddleware.js
  webapp/graphql/groups.js
Labels: bug, frontend

#5591 fix: 🍰 Add Space In Register Box
  webapp/components/Registration/RegistrationSlideCreate.vue
  webapp/components/Registration/RegistrationSlideEmail.vue
  webapp/components/Registration/RegistrationSlideInvite.vue
  webapp/components/Registration/RegistrationSlideNoPublic.vue
  webapp/components/Registration/RegistrationSlideNonce.vue
Labels: frontend

#5599 feat: Restrict Comments on Posts in Groups
  backend/src/middleware/permissionsMiddleware.js
  backend/src/schema/resolvers/postsInGroups.spec.js
Labels: backend

#5600 docs: 🍰 Add Live Demo To Main Readme
  README.md
Labels: documentation

#5607 fix: 🍰 Comments On Posts In Groups In Webapp
  webapp/pages/post/_id/_slug/index.vue
Labels: frontend

#5546 feat: 🍰 Header Menu To Component And Other Refinements
  webapp/components/HeaderMenu/HeaderMenu.vue
  webapp/components/PageFooter/PageFooter.vue
  webapp/layouts/default.vue
Labels: frontend, refactor, design, Yunite

#5590 feat: 🍰 Footer And Header Links Configurable To Have External Link Target
  webapp/components/Group/GroupMember.vue
  webapp/components/HeaderMenu/HeaderMenu.vue
  webapp/components/PageFooter/PageFooter.spec.js
  webapp/components/_new/features/PageParamsLink/PageParamsLink.vue
  webapp/components/utils/InternalPages.js
  webapp/components/utils/PageParams.js
  webapp/constants/headerMenu.js
  webapp/constants/links.js
  webapp/mixins/internalPageMixins.js
Labels: frontend

#5597 refactor: 🍰 Refactor Design Of Category Filter In Filter Menu
  .github/workflows/test.yml
  webapp/components/FilterMenu/CategoriesFilter.spec.js
  webapp/components/FilterMenu/CategoriesFilter.vue
  webapp/components/FilterMenu/EmotionsFilter.spec.js
  webapp/components/FilterMenu/EmotionsFilter.vue
  webapp/components/FilterMenu/FilterMenu.vue
  webapp/components/FilterMenu/FilterMenuSection.vue
  webapp/components/FilterMenu/FollowingFilter.spec.js
  webapp/components/FilterMenu/FollowingFilter.vue
  webapp/components/FilterMenu/LanguagesFilter.spec.js
  webapp/components/FilterMenu/LanguagesFilter.vue
  webapp/components/HeaderMenu/HeaderMenu.vue
  webapp/graphql/CategoryQuery.js
Labels: frontend
