Repository Ocelot-Social-Community/Ocelot-Social, pull requests merged in 2022-07, with the labels that each got.

#5058 chore: 🍰 Release v1.0.8
  CHANGELOG.md
  backend/package.json
  package.json
  webapp/maintenance/source/package.json
  webapp/package.json
Labels: core, devops

#5076 chore: 🍰 Fix `ocelotsocialnetwork/webapp:latest` And `ocelotsocialnetwork/backend:latest` On Start In Cluster
  DOCKER_MORE_CLOSELY.md
  SUMMARY.md
  backend/Dockerfile
  webapp/Dockerfile
Labels: bug, documentation, core, devops, docker

#5073 chore: 🍰 Change `image` Entries In Docker Compose Files And Fix Apple M1 Problem
  DOCKER_MORE_CLOSELY.md
  docker-compose.apple-m1.override.yml
  docker-compose.maintenance.yml
  docker-compose.override.yml
  docker-compose.test.yml
  docker-compose.yml
  webapp/maintenance/README.md
Labels: bug, documentation, question, core, devops, docker, discussion, refactor

#5088 5079 legends for search field
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/locales/es.json
  webapp/locales/fr.json
  webapp/locales/it.json
  webapp/locales/nl.json
  webapp/locales/pl.json
  webapp/locales/pt.json
  webapp/locales/ru.json
Labels: frontend, refactor

#5090 docs: 🍰 Add Neo4j Docu For Important Commands
  DOCKER_MORE_CLOSELY.md
  neo4j/README.md
Labels: documentation, core, devops

#5091 change footer version-link
  webapp/components/PageFooter/PageFooter.vue
Labels: frontend, refactor

#5080 chore: 🍰 Automatic Deployment To `stage.ocelot.social` On Push To `master` Branch
  .github/workflows/publish.yml
  backend/src/config/index.js
  backend/src/db/clean.js
  backend/src/db/seed.js
Labels: documentation, core, devops

#5095 chore: 🍰 Release v1.0.9
  CHANGELOG.md
  backend/package.json
  package.json
  webapp/maintenance/source/package.json
  webapp/package.json
Labels: devops

#5097 chore: 🍰 Betters Automatic Deployment To `stage.ocelot.social` On Push To `master` Branch
  .github/workflows/publish.yml
Labels: core, devops
