Repository Ocelot-Social-Community/Ocelot-Social, pull requests merged in 2023-09, with the labels that each got.

#6702 chore(release): release v3.0.3 – fix chat avatar error, adjust layout of filter and enable e-mail dkim
  CHANGELOG.md
  backend/package.json
  package.json
  webapp/maintenance/source/package.json
  webapp/package.json
Labels: devops

#6704 fix(backend): metascraper crash
  backend/src/schema/resolvers/embeds/scraper.ts
Labels: bug, service: backend, dependencies

#6720 fix(backend): fix post language detection
  backend/src/middleware/languages/languages.spec.ts
  backend/src/middleware/languages/languages.ts
Labels: bug, service: backend

#6662 fix(other): fix backup script for neo4j v4
  deployment/scripts/cluster.backup.sh
Labels: bug

#6731 chore(other): use dkim values in helm script of backend
  deployment/src/kubernetes/templates/backend/ConfigMap.yml
Labels: devops

#6733 chore(release): release v3.1.0 – use of dkim in deployment
  CHANGELOG.md
  backend/package.json
  package.json
  webapp/maintenance/source/package.json
  webapp/package.json
Labels: devops

#6382 test(other): update cypress related packages
  cypress/support/step_definitions/Post.Comment/I_comment_the_following.js
  cypress/support/step_definitions/Post.Create/I_choose_{string}_as_the_title.js
  cypress/support/step_definitions/Post.Create/the_post_was_saved_successfully.js
  cypress/support/step_definitions/common/I_choose_the_following_text_as_content.js
  package.json
  yarn.lock
Labels: devops

#6724 refactor(backend): remove redundant package metascraper-audio from backend
  backend/package.json
  backend/yarn.lock
Labels: service: backend, dependencies, refactor

#6758 chore(other): upgrade node version in '.nvmrc' files to v20.6.0
  .nvmrc
  backend/.nvmrc
  webapp/.nvmrc
Labels: devops

#6755 chore(other): add tail command as template comment to `docker-compose.yml`
  docker-compose.yml
  neo4j/README.md
Labels: bug, devops

#6763 chore(release): release v3.1.1 – move dkim to secrets and fix search etc.
  CHANGELOG.md
  backend/package.json
  package.json
  webapp/maintenance/source/package.json
  webapp/package.json
Labels: devops
