Repository Ocelot-Social-Community/Ocelot-Social, pull requests merged in 2023-10, with the labels that each got.

#6780 fix(backend): cypher statement in user locales unit test
  backend/src/schema/resolvers/users/location.spec.ts
Labels: devops

#6779 fix(other): kubernetes error by degrading node version from v20.7.0 to v20.2.0
  .nvmrc
  backend/.nvmrc
  backend/Dockerfile
  backend/src/schema/resolvers/users/location.spec.ts
  neo4j/Dockerfile
  webapp/.nvmrc
  webapp/Dockerfile
  webapp/Dockerfile.maintenance
Labels: devops

#6782 chore(release): release v3.1.2 - fix kubernetes deployment by degrade Node version from v20.7.0 to v20.2.0
  CHANGELOG.md
  backend/package.json
  package.json
  webapp/maintenance/source/package.json
  webapp/package.json
Labels: bug, devops

#6729 fix(other): fix link in `deployment/TODO-next-update.md` to `deployment/deployment-values.md`
  deployment/TODO-next-update.md
Labels: bug, devops

#6786 docs(other): refine deployments `docker-compose.yml` in deployment and main folder
  deployment/docker-compose.yml
  deployment/src/kubernetes/Backup.md
  docker-compose.yml
  neo4j/README.md
Labels: devops

#6809 fix(other): increase cypress timeouts
  cypress/cypress.config.js
Labels: bug, service: e2e

#6807 fix(webapp): make filter menu visible if categories are inactive
  webapp/components/FilterMenu/FilterMenuComponent.vue
  webapp/pages/index.vue
Labels: bug

#6808 refactor(webapp): replace deprecated jest methods in webapp unit tests
  webapp/components/DonationInfo/DonationInfo.spec.js
  webapp/components/Group/GroupMember.spec.js
  webapp/components/LoginForm/LoginForm.spec.js
  webapp/components/PostTeaser/PostTeaser.spec.js
  webapp/pages/index.spec.js
  webapp/pages/login.spec.js
  webapp/pages/logout.spec.js
  webapp/pages/map.spec.js
  webapp/pages/password-reset.spec.js
  webapp/pages/post/edit/_id.spec.js
  webapp/pages/registration.spec.js
  webapp/pages/terms-and-conditions-confirm.spec.js
Labels: service: webapp, refactor
