Repository Ocelot-Social-Community/Ocelot-Social, pull requests merged in 2023-11, with the labels that each got.

#6796 fix(other): fix and refine docs and add kubernetes cluster installation script
  README.md
  deployment/scripts/cluster.install.sh
  deployment/src/kubernetes/DigitalOcean.md
  deployment/src/kubernetes/README.md
Labels: devops

#6182 chore(other): add script to set neo4j in offline-mode and back in online-mode
  deployment/scripts/cluster.backup.sh
  deployment/scripts/cluster.neo4j.sh
Labels: devops

#6802 docs(other): fix divers links in readmes
  README.md
  SUMMARY.md
  backend/graphql.md
  backend/src/graphql/GraphQL-Playground.md
  backend/testing.md
  edit-this-documentation.md
Labels: docu, devops

#6784 fix(webapp): event date format
  backend/jest.config.js
  backend/src/db/migrations/20231017141022-fix-event-dates.ts
  backend/src/schema/resolvers/helpers/events.ts
  backend/src/schema/resolvers/posts.spec.ts
  webapp/components/ContributionForm/ContributionForm.vue
Labels: bug, service: webapp

#6814 feat(backend): coverage backend to 90%
  backend/jest.config.js
  backend/src/schema/resolvers/notifications.spec.ts
Labels: service: backend

#6824 feat(other): add documentation check to CI
  .github/file-filters.yml
  .github/workflows/check-documentation.yml
  .github/workflows/mlc_config.json
Labels: feature, devops

#6864 fix(backend): expired jwt in unit test
  backend/src/jwt/decode.spec.ts
Labels: bug, service: backend

#6856 build(other): fix cucumber dependency deprecation
  package.json
  yarn.lock
Labels: dependencies, service: e2e

#6857 refactor(other): remove unused packages and scripts
  backend/package.json
  backend/yarn.lock
  package.json
Labels: dependencies

#6848 chore(other): upgrade cert-manager version
  deployment/scripts/cluster.install.sh
  deployment/src/kubernetes/README.md
  neo4j/README.md
Labels: devops
