Repository Ocelot-Social-Community/Ocelot-Social, pull requests merged in 2024-01, with the labels that each got.

#6850 feat(webapp): improve registration slide nonce text
  webapp/components/EnterNonce/EnterNonce.vue
  webapp/components/Registration/RegistrationSlideNonce.vue
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/locales/fr.json
Labels: refactor, project: sender.fm

#6940 docs(other): add new neo4j env for default database name to readmes
  deployment/TODO-next-update.md
  deployment/deployment-values.md
  neo4j/.env.template
Labels: docu, devops, service: docker, docker

#6825 refactor(other): fix broken links in documentation
  .github/workflows/check-documentation.yml
  .github/workflows/mlc_config.json
  CONTRIBUTING.md
  deployment/Minikube.md
  deployment/README.md
  deployment/src/kubernetes/DigitalOcean.md
Labels: docu, refactor

#6953 feat(webapp): add chat item to avatar navigation menu and change title of notification by removing `All …`
  webapp/components/AvatarMenu/AvatarMenu.spec.js
  webapp/components/AvatarMenu/AvatarMenu.vue
  webapp/components/ChatNotificationMenu/ChatNotificationMenu.vue
  webapp/components/Group/GroupButton.vue
  webapp/components/Map/MapButton.vue
  webapp/components/NotificationMenu/NotificationMenu.vue
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/locales/es.json
  webapp/locales/fr.json
  webapp/locales/it.json
  webapp/locales/nl.json
  webapp/locales/pl.json
  webapp/locales/pt.json
  webapp/locales/ru.json
Labels: feature, service: webapp, features_chat, chat

#6971 fix(webapp): fix footer links
  webapp/constants/links.js
Labels: bug, service: webapp

#6957 docs(other): add description for a 1-click install and usage of kubernetes dashboard
  deployment/src/kubernetes/DigitalOcean.md
Labels: docu, project: yunite, project: wir.social, project: freilernen.social, project: sender.fm

#6972 fix(other): revert "remove temporarily some *.ocelot.social link from the readmes…"
  CONTRIBUTING.md
  README.md
  deployment/README.md
Labels: bug, service: webapp
