Repository Ocelot-Social-Community/Ocelot-Social, pull requests merged in 2024-02, with the labels that each got.

#6956 fix(webapp): fix wrong content menu position on group profile page
  webapp/pages/groups/_id/_slug.vue
Labels: bug, service: webapp

#6987 feat(other): frontend workflows & test suites
  .github/dependabot.yml
  .github/file-filters.yml
  .github/workflows/frontend.deploy.chromatic.yml
  .github/workflows/frontend.test.build.code.yml
  .github/workflows/frontend.test.build.docs.yml
  .github/workflows/frontend.test.build.storybook.yml
  .github/workflows/frontend.test.lint.code.yml
  .github/workflows/frontend.test.unit.code.yml
  .github/workflows/lint_pr.yml
  .github/workflows/test.lint_pr.yml
  frontend/.github/dependabot.yml
  frontend/.github/file-filters.yml
Labels: feature, devops

#7002 chore(other): release v3.2.0 – redesign of newsfeed, fix event datetime utc problem etc.
  CHANGELOG.md
  backend/package.json
  frontend/package.json
  package.json
  webapp/maintenance/source/package.json
  webapp/package.json
Labels: devops

#7016 refactor(other): adapt docs website navbar and footer to ocelot.social website
  .vuepress/config/theme.js
  package-lock.json
  package.json
Labels: docu, refactor, design

#7014 refactor(other): set ocelot color for docs website
  .vuepress/styles/palette.scss
Labels: docu, refactor, design

#7017 chore(frontend): update frontend boilerplate
  frontend/package-lock.json
  frontend/package.json
  frontend/renderer/+config.ts
Labels: devops, service: frontend

#7027 chore(frontend): update frontend boilerplate 26 02
  .github/file-filters.yml
  .github/workflows/frontend.test.build.docker.yml
  frontend/.vuepress/config.ts
  frontend/Dockerfile
  frontend/package-lock.json
  frontend/package.json
Labels: devops, service: frontend
