Repository Ocelot-Social-Community/Ocelot-Social, pull requests merged in 2024-09, with the labels that each got.

#7818 refactor(frontend): remove chromatic
  .github/workflows/frontend.deploy.chromatic.yml
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
Labels: refactor, service: frontend

#7819 refactor(other): remove package wait-on
  package.json
  yarn.lock
Labels: dependencies, refactor

#7848 chore(other): adjust docs for deployment, neo4j cypher commands, and have new scripts
  deployment/deployment.md
  deployment/scripts/cluster.backend-bash.sh
  deployment/scripts/cluster.dashboard-token.sh
  deployment/scripts/cluster.dashboard-tunnel.sh
  deployment/scripts/cluster.neo4j-bash.sh
  deployment/src/kubernetes/DigitalOcean.md
  neo4j/README.md
Labels: devops
